<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Gajanan" failures="1" tests="3" name="Test" time="69.644" errors="0" timestamp="2023-12-02T16:52:42 IST">
  <testcase classname="ai.aptipro.tests.landingPageTests" name="clickOnSignInButton" time="1.352">
    <failure type="java.lang.AssertionError" message="expected [http://dev.aptipro.ai/signina] but found [http://dev.aptipro.ai/signin]">
      <![CDATA[java.lang.AssertionError: expected [http://dev.aptipro.ai/signina] but found [http://dev.aptipro.ai/signin]
at ai.aptipro.tests.landingPageTests.clickOnSignInButton(landingPageTests.java:17)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 33 stack frames]]>
    </failure>
  </testcase> <!-- clickOnSignInButton -->
  <testcase classname="ai.aptipro.tests.landingPageTests" name="clickOnSignUpButton" time="0.273"/>
  <testcase classname="ai.aptipro.tests.landingPageTests" name="clickonGetStartedButton" time="0.355"/>
</testsuite> <!-- Test -->
